# cloudbuild.yamlsteps:
  - name: node:12.18.3
    entrypoint: yarn
    args: ["install"]
  - name: node:12.18.3
    entrypoint: yarn
    args: ["build", "start"]
  - name: "gcr.io/cloud-builders/gcloud"
    args: ["app", "deploy"]
  timeout: "1600s"